### ISSUE TITLE
Warning when running on Android: "Setting a timer for a long period of time, i.e. multiple minutes..."

### ISSUE THREAD

**Issue by trollevsy** [samhamra/friska-react-native#16]
Tror det är firebaserelaterat, detta ser ut att handla om något snarlikt: https://github.com/firebase/firebase-js-sdk/issues/97

**Comment by samhamra** [comment]
Det verkar vara ett problem med firebase, se: https://github.com/firebase/firebase-js-sdk/issues/97

**Comment by trollevsy** [comment]
Haha ja jag nämnde det! Hur kan man lösa det då? Inte så bra att det kommer upp hela tiden
